Repository izemaghilas/tp-github, pull requests merged in 2022-01, with the labels that each got.

#6 authentication service
  AuthService.php
Labels: enhancement

#5 payment service
  payment.php
Labels: enhancement

#8 modified readme
  README.md
Labels: documentation

#11 badges
  README.md
Labels: upgrade
